# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-11-01 20:38
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_auto_20161101_1535'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='homepage',
            name='body_en',
        ),
    ]
